// GENERATED by build-data.py — bundled content baseline for js/content.js.
// version = epoch-ms of this build; the client applies remote content only if newer.
export const BUNDLED_CONTENT = {"version": 1787158707651, "hash": "0ffbb20df55d", "generated": "2026-08-19T16:58:27.651795+00:00"};
