// GENERATED by build-data.py — bundled content baseline for js/content.js.
// version = epoch-ms of this build; the client applies remote content only if newer.
export const BUNDLED_CONTENT = {"version": 1786888381161, "hash": "42759b5942bf", "generated": "2026-08-16T13:53:01.161405+00:00"};
