// GENERATED by build-data.py — bundled content baseline for js/content.js.
// version = epoch-ms of this build; the client applies remote content only if newer.
export const BUNDLED_CONTENT = {"version": 1786822917592, "hash": "6cd34be36a97", "generated": "2026-08-15T19:41:57.592227+00:00"};
