/**
 * SHINE PWA — Service Worker
 *
 * Offline strategy using 4 named caches:
 *   1. App shell (HTML, CSS, JS)     — cache-first, precached on install
 *   2. Card tier + CDN full-res      — cards precached from card-manifest.json;
 *                                       full-res (cdn.muralquest.app) cached on view
 *   3. Map tiles (CARTO)             — network-first, cached for offline fallback
 *   4. Fonts & CDN (Google, Leaflet) — cache-first, cached on first fetch
 *
 * Cache versioning: bump the version suffix to force a cache refresh on deploy.
 * The activate handler auto-deletes old caches not in the `keep` list.
 *
 * v1.5 image split: grid/map/pins use the bundled 384px WebP card tier
 * (images/cards/, generated by scripts/generate-cards.py → card-manifest.json).
 * Full-res photos live on the CDN; the detail view loads them and they cache here.
 * The OTA content manifest (content.json) is bypassed entirely (see fetch handler).
 */

const CACHE_NAME = 'shine-v146';       // App shell — bump on code changes
const TILE_CACHE = 'shine-tiles-v1';  // Map tiles — rarely needs bumping
const IMG_CACHE = 'shine-images-v10'; // Card tier + CDN full-res — bumped for v1.5 image split
const FONT_CACHE = 'shine-fonts-v1';  // CDN fonts/libs — rarely needs bumping

// These files are precached on install — the app works offline immediately
const SHELL_ASSETS = [
  './',
  './index.html',
  './css/app.css',
  './css/fonts.css',
  './js/app.js',
  './js/data.js',          // bundled content fallback
  './js/content.js',       // v1.5 OTA content layer
  './js/content-meta.js',  // v1.5 bundled content version marker
  './js/photos.js',
  './manifest.json',
  './card-manifest.json',
  './images/icons/icon-192.png',
  './images/icons/icon-512.png'
];


// Install: precache the app shell + the bundled card tier (~3MB of 384px WebP,
// read from card-manifest.json so it stays in sync automatically — no hand-kept
// list). Full-res photos are NOT precached; they live on the CDN and get cached
// on first view in the detail page (see cacheFirstImage). Each card is cached
// individually so one failure doesn't block the rest.
self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE_NAME).then(c => c.addAll(SHELL_ASSETS))
      .then(() => fetch('./card-manifest.json').then(r => (r.ok ? r.json() : [])).catch(() => []))
      .then(cards => caches.open(IMG_CACHE).then(cache =>
        Promise.all(cards.map(url =>
          cache.add(url).catch(err => console.warn('SW: failed to cache card', url, err))
        ))
      ))
      .then(() => self.skipWaiting())
  );
});

// Activate: delete any old caches not in the current version list
// Then tell all open tabs to reload so they get fresh files
self.addEventListener('activate', (e) => {
  const keep = [CACHE_NAME, TILE_CACHE, IMG_CACHE, FONT_CACHE];
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => !keep.includes(k)).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
     .then(() => self.clients.matchAll({ type: 'window' }))
     .then(clients => clients.forEach(c => c.postMessage({ type: 'SW_UPDATED' })))
  );
});

// Fetch: route requests to the appropriate caching strategy based on URL
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);

  // Skip non-GET requests
  if (e.request.method !== 'GET') return;

  // v1.5 OTA content manifest — NEVER let the service worker cache or serve it.
  // content.js fetches this (cache: 'no-store') to detect published updates; if the
  // SW cached it, the catch-all cacheFirst below would serve a stale copy forever
  // and shadow every OTA update. Bypass entirely (no respondWith) so the browser's
  // own no-store fetch hits the network. Offline is handled in content.js (falls
  // back to the localStorage cache, then the bundled data.js).
  if (url.pathname.endsWith('/content.json')) return;

  // Tools (route-editor, yaml-editor) — always network, never cache
  if (url.pathname.includes('/tools/')) return;

  // Google Fonts + Leaflet CDN — cache first (rarely changes)
  if (url.hostname.includes('fonts.googleapis.com') || url.hostname.includes('fonts.gstatic.com') || url.hostname.includes('unpkg.com')) {
    e.respondWith(cacheFirstCDN(e.request));
    return;
  }

  // Map tiles — network first so you get current tiles, fall back to cached for offline
  if (url.hostname.includes('tile') || url.hostname.includes('carto') || url.hostname.includes('basemaps')) {
    e.respondWith(networkFirstTile(e.request));
    return;
  }

  // Mural images — cache first (precached on install, plus any new ones cached on fetch)
  if (url.pathname.includes('/images/') || e.request.destination === 'image') {
    e.respondWith(cacheFirstImage(e.request));
    return;
  }

  // App shell — cache first, stripping query strings for matching
  e.respondWith(cacheFirst(e.request));
});

/** Cache-first for app shell. Strips query strings so ?v=14 matches the precached entry. */
async function cacheFirst(req) {
  // Try exact match first, then try without query string
  let c = await caches.match(req);
  if (!c) {
    const url = new URL(req.url);
    if (url.search) {
      url.search = '';
      c = await caches.match(url.href);
    }
  }
  if (c) return c;
  try {
    const r = await fetch(req);
    if (r.ok) { const cache = await caches.open(CACHE_NAME); cache.put(req, r.clone()); }
    return r;
  } catch {
    return req.mode === 'navigate' ? caches.match('./index.html') : new Response('Offline', {status:503});
  }
}

/** Cache-first for CDN assets (fonts, Leaflet). Stored in separate FONT_CACHE. */
async function cacheFirstCDN(req) {
  const c = await caches.match(req);
  if (c) return c;
  try {
    const r = await fetch(req);
    if (r.ok) { const cache = await caches.open(FONT_CACHE); cache.put(req, r.clone()); }
    return r;
  } catch { return new Response('', {status:503}); }
}

/** Cache-first for images. Most are precached; new ones get cached on first fetch. */
async function cacheFirstImage(req) {
  const c = await caches.match(req);
  if (c) return c;
  try {
    const r = await fetch(req);
    if (r.ok) { const cache = await caches.open(IMG_CACHE); cache.put(req, r.clone()); }
    return r;
  } catch { return new Response('', {status:503}); }
}

/** Network-first for map tiles. Caches successful fetches; serves stale cache when offline. */
async function networkFirstTile(req) {
  try {
    const r = await fetch(req);
    if (r.ok) { const cache = await caches.open(TILE_CACHE); cache.put(req, r.clone()); }
    return r;
  } catch {
    const c = await caches.match(req);
    return c || new Response('', {status:503});
  }
}
